# This is a docker compose file to bring allure services up which will be sending results to
# This is not part of the docker compose for selenium because we want this service to be always be running
# More info here: https://github.com/fescobar/allure-docker-service/tree/master
version: '3'
services:
  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: 1
      KEEP_HISTORY_LATEST: 25
    ports:
      - "5050:5050"
    volumes:
      - ./projects:/app/projects