pipeline{
    agent any
    stages{
        stage("Pull Selenium test docker Image"){
            steps{
                sh "docker pull aothmana/selenium-grid-python "
            }
        }
        stage("Start Allure Server"){
            steps{
                sh "docker-compose -f docker-compose-allure.yml up -d allure"
            }
        }
        stage("Run Grid"){
            steps{
                sh"ALLURE_IP_ADDRESS=192.168.1.103 docker-compose -f docker-compose.yml up -d  selenium-hub  selenium-chrome  selenium-firefox"
            }
        }
    }
    post{
        always{
            sh"docker-compose down"
        }
    }
}