pipeline{
    agent any
    stages{
        stage("Pull Selenium test docker Image"){
            steps{
                sh "docker pull aothmana/selenium-grid-python "
            }
        }
        stage("Start Allure Server"){
            steps{
                sh "docker-compose -f docker-compose-allure.yml up"
            }
        }
        stage("Run test"){
            steps{
                sh"ALLURE_IP_ADDRESS=192.168.1.103 docker-compose -d -f docker-compose.yml up"
            }
        }
    }
    post{
        always{
            sh"docker-compose down"
        }
    }
}